# Generated by Django 5.0.6 on 2024-06-18 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="teamName",
            field=models.CharField(default="SD", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="teamSlogan",
            field=models.CharField(default="sdf", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="updatedDate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
