# Generated by Django 5.0.6 on 2024-06-19 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_coach_game_tournament_team_displayname_team_rank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="coach",
        ),
        migrations.AddField(
            model_name="coach",
            name="team",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.team"
            ),
        ),
    ]
