# Generated by Django 5.0.6 on 2024-06-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_team_coach_coach_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamestat",
            name="score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="height",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="rank",
            field=models.IntegerField(null=True),
        ),
    ]
