# Generated by Django 5.0.6 on 2024-06-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_gamestat_score_alter_player_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstat",
            name="impact_index",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="playerstat",
            name="score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="rank",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="slogan",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="mascot",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
