# Generated by Django 5.0.6 on 2024-06-19 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_playerstat_impact_index_alter_playerstat_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamestat",
            name="playerofthematch",
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamestats",
                to="core.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teamstats",
                to="core.team",
            ),
        ),
    ]
