# Generated by Django 5.0.6 on 2024-06-21 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_gamestat_playerofthematch_alter_gamestat_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="team",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coach",
                to="core.team",
            ),
        ),
    ]
