# Generated by Django 5.0.6 on 2024-06-21 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_coach_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coach",
            name="team",
        ),
        migrations.AddField(
            model_name="team",
            name="coach",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team",
                to="core.coach",
            ),
        ),
    ]
