# Generated by Django 5.0.6 on 2024-06-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_role",
            name="is_logged_in",
            field=models.BooleanField(default=False),
        ),
    ]
