# Generated by Django 5.0.6 on 2024-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_userstat_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstat",
            name="logout_at",
            field=models.DateTimeField(null=True),
        ),
    ]
