# Generated by Django 5.0.6 on 2024-06-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_userstat_logout_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="userrole",
            field=models.CharField(
                choices=[(0, "Admin"), (1, "Coach"), (2, "Player")], max_length=3
            ),
        ),
    ]
