# Generated by Django 5.0.6 on 2024-06-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_userrole_userrole"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrole",
            name="is_logged_in",
        ),
        migrations.AlterField(
            model_name="userrole",
            name="userrole",
            field=models.IntegerField(
                choices=[(0, "Admin"), (1, "Coach"), (2, "Player")], max_length=2
            ),
        ),
    ]
