# Generated by Django 5.0.6 on 2024-06-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remove_userrole_is_logged_in_alter_userrole_userrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="userrole",
            field=models.IntegerField(
                choices=[(0, "Admin"), (1, "Coach"), (2, "Player")]
            ),
        ),
    ]
